social_title = "More than meets the eye: Understanding how the brain controls social gaze"
social_article = """
For animals like primates, the act of gazing plays a key role in social interaction, used to both send and gather information. In a new study, Yale scientists uncover two brain regions that contribute to this type of social attention.
The findings yield important insight into how this dynamic behavior arises and might be used to boost social behavior in disorders like autism in which engaging in social attention can be challenging, researchers say.
The findings were published May 31 in the journal Neuron.
For primates, social gaze is an integral part of social interaction, says Steve Chang, an associate professor of psychology and neuroscience in Yale’s Faculty of Arts and Sciences and senior author of the study.
“For example, monkeys want to see what others are looking at because there might be more resource opportunities,” said Chang. “But eye contact that lasts a long time could also be a threatening gesture. So there’s this intricate balance of when to look at the eyes of another to get information but not send the wrong information.”
In a previous study, Chang and his colleagues identified brain regions in the prefrontal-amygdala brain networks where neural activity increased as monkeys gazed at each other. For the new study, they wanted to determine to what extent these regions caused social gazing behavior.
To do so, the researchers paired two rhesus macaque monkeys and then used infrared cameras to track the eye positions of both monkeys. When one of the monkeys looked at the other’s eyes, it received a tiny, real-time stimulation in one of three brain regions. The researchers then tracked whether and how the stimulated monkey’s gaze changed.
They found that after receiving stimulation in one of the regions — a prefrontal cortical region called the orbitofrontal cortex — monkeys’ spontaneous gazes were more concentrated around their partners eyes for the next several seconds and the time in between gazes was much shorter, compared with monkeys that did not receive a stimulation.
“Stimulation in this region also reduced the amount of time it took for a monkey to reciprocate another’s gaze,” said Chang. “But none of these findings occurred when monkeys were in a non-social interaction, looking at a moving dot rather than another monkey’s eyes.”
Stimulation within the other two brain regions — the dorsomedial prefrontal cortex and the gyrus of the anterior cingulate cortex — did not yield the same effects.
However, stimulation to the dorsomedial prefrontal cortex did have a unique longer-term effect not observed within the other regions. Over the stimulation sessions, which lasted 1.5 hours, stimulation to the dorsomedial prefrontal cortex altered how gazes were exchanged between two monkeys.
“The gazes of partner monkeys were interacting over time in a kind of leader-follower pattern,” said Chang. “Over the course of the stimulations, this relationship strengthened, but only with stimulations to the dorsomedial prefrontal cortex.”
Together, the findings reveal the important contributions these two brain regions offer when it comes to both momentary and long-term social gaze interaction. Knowing how these regions contribute to social interactions, and social gaze specifically, reveals where interventions could be focused to boost social behavior where it’s diminished, said Chang.
“We can envision a future therapeutic approach that builds on these findings using a social brain-computer interface,” he said, “where we target these regions to enhance in-the-moment and long-term social attention.”
"""

social_article_link = "https://news.yale.edu/2024/05/31/more-meets-eye-understanding-how-brain-controls-social-gaze"

translated_social_article = """
Have you ever wondered why animals like monkeys and apes spend so much time looking at each other? It turns out that gazing plays a really important role in how they interact with one another. When they look at each other, they're not just being curious - they're actually sending and gathering information! In a new study, scientists from Yale University discovered two parts of the brain that help make this special kind of social attention happen.
The findings are exciting because they help us understand how this fascinating behavior works. Plus, they might even be used to help people with disorders like autism, who sometimes find it challenging to engage in social attention.
The study was published on May 31 in a scientific journal called Neuron.
Steve Chang, one of the main researchers, explains why social gaze is so important for primates like monkeys and apes:
"For example, monkeys want to see what others are looking at because there might be more resource opportunities," said Chang. "But eye contact that lasts a long time could also be a threatening gesture. So there's this intricate balance of when to look at the eyes of another to get information but not send the wrong information."
In an earlier study, Chang and his team found that certain parts of the brain became more active when monkeys looked at each other. This time, they wanted to figure out if those brain regions actually caused the monkeys to gaze at each other socially.
To find out, the researchers put two rhesus macaque monkeys together and used special cameras to track where their eyes were looking. Whenever one monkey looked at the other's eyes, the researchers gave it a tiny, real-time stimulation in one of three brain regions. Then, they watched to see if and how the stimulated monkey's gaze changed.
They discovered that when one specific brain region called the orbitofrontal cortex was stimulated, the monkeys spent more time looking at their partner's eyes for the next several seconds. The time between gazes was also much shorter compared to monkeys that didn't receive the stimulation.
"Stimulation in this region also reduced the amount of time it took for a monkey to reciprocate another's gaze," said Chang. "But none of these findings occurred when monkeys were in a non-social interaction, looking at a moving dot rather than another monkey's eyes."
Stimulating the other two brain regions didn't have the same effects. However, stimulating a region called the dorsomedial prefrontal cortex did have a unique longer-term effect. Over the course of the 1.5-hour stimulation sessions, the gazes of the two monkeys started to interact in a leader-follower pattern. This relationship got stronger over time, but only when the dorsomedial prefrontal cortex was stimulated.
These findings show how these two brain regions contribute to both short-term and long-term social gaze interaction. By understanding how these regions work, scientists might be able to find ways to boost social behavior in people who struggle with it, like those with autism.
"We can envision a future therapeutic approach that builds on these findings using a social brain-computer interface," Chang said, "where we target these regions to enhance in-the-moment and long-term social attention."
"""

calcium_channel_link = "https://medicine.yale.edu/news-article/study-reveals-how-calcium-channel-mutations-lead-to-cognitive-dysfunction/"

calcium_channel_title = "Study Reveals How Calcium Channel Mutations Lead to Cognitive Dysfunction"

calcium_channel_article = """A new study from Yale School of Medicine has shown that the neurons that generate higher cognition, and are a target of pathology in Alzheimer's disease and mental disorders such as schizophrenia, express an enrichment of calcium-related proteins that helps to explain their vulnerability to disease. This finding builds on previous studies that determined that alterations in a gene known as CACNA1C are linked to increased risk of cognitive impairment and mental illness.


Amy Arnsten, PhD

CACNA1C encodes calcium channels that enable the flow of calcium ions into neurons. For years, researchers have known that gain-of-function mutations in this gene, which can create more of these calcium channels, raise the risk for cognitive disorders, but they did not understand why this increase was harmful to the prefrontal cortex, which generates higher cognition and the executive functions.

Now, a Yale team has discovered that excessive calcium channel activation in the prefrontal cortex is associated with reduced neuronal firing, which in turn hinders cognition. The researchers published their findings in JAMA Psychiatry on May 22.

“Trying to learn what causes these complex cognitive disorders is an enormous challenge, especially when they’re attacking our most recently evolved brain circuits — you can’t just mimic this in a dish,” says Amy Arnsten, PhD, Albert E. Kent Professor of Neuroscience, who is the study’s senior author. “Studies like this are some of the rare bridges between the molecular biology and the symptoms we see in humans, allowing us to understand what these circuits need to function properly, as well as their vulnerabilities.”

A link between calcium and abstract thought
To learn more about how CACNA1C mutations could increase risk of cognitive disorders, the researchers turned their attention to a group of cells known as layer III pyramidal cells. These are neurons in the prefrontal cortex that are highly important for the brain’s executive functions, such as abstract thinking and working memory. This group of cells is vulnerable to atrophy and neurodegeneration while, interestingly, their nearby neighbors typically remain unaffected.

Arnsten’s team employed a variety of methods, including running transcriptomic analyses (explorations of all RNA molecules in a cell) of human and animal pyramidal cells, to investigate these neurons’ susceptibility to dysfunction and their potential link to CACNA1C alteration. The researchers found that these neurons expressed signatures indicative of high calcium, including an assembly of calcium-related proteins.

The team then embarked on more in-depth studies of these molecules, including in animal models. Their findings suggest that increased calcium in pyramidal cells is necessary for higher cognition. “We found evidence that these neurons require higher calcium to maintain their firing over many seconds to represent information that isn’t actually happening,” says Arnsten. “That’s the foundation of abstract thought.”

The researchers then infused a drug that mimics the stress response next to the prefrontal neurons. They found that stress activated the calcium channels, which in turn opened nearby potassium channels to stop the neurons from firing. “Ever have your mind go blank when you get bad news or have to do public speaking?” said Arnsten. “ That’s likely involving this mechanism.”

Clues for treating schizophrenia and Alzheimer’s disease
These findings have significant clinical implications for understanding the pathologies of cognitive disorders, including schizophrenia and Alzheimer’s disease, both of which are characterized by profound prefrontal cortex dysfunction. Previous research has shown, for example, that gain-of-function mutations in CACNA1C raise risk for schizophrenia. The study offers evidence that the increase in calcium resulting from these mutations can lead to the atrophy associated with the condition.

Furthermore, the team’s transcriptomic analyses revealed that the pyramidal cells contain calbindin, a calcium-binding protein that plays an essential role in maintaining calcium homeostasis. However, over time, this important balance can be altered by aging or inflammation. Prior research has shown that elevated calcium can propel tau pathology, a characteristic of Alzheimer’s disease, in which tau proteins become hyperphosphorylated and form tangles in the brain. Thus, as pyramidal cells in the prefrontal cortex age and lose calbindin, they become vulnerable to the neurodegenerative disorder.

Arnsten hopes these insights will lead to greater understanding of and, ultimately, better treatments for these conditions. “We’ve uncovered big clues about which brain cells are most vulnerable and which are resilient,” she says. “If we can learn why certain cells are vulnerable, that also gives us clues about how to protect them.”"""

translated_calcium_article = """A new study from Yale School of Medicine has discovered that certain brain cells, called neurons, which help us think and reason, are more likely to be affected by diseases like Alzheimer's and mental disorders like schizophrenia. These neurons have a lot of special proteins related to calcium, which helps explain why they are more vulnerable to getting sick.
Scientists have known for a while that changes in a gene called CACNA1C, which helps control the flow of calcium into neurons, can increase the risk of problems with thinking and mental health. But they didn't understand why having more calcium channels from this gene was harmful to a part of the brain called the prefrontal cortex, which is important for higher thinking and decision-making.
The Yale team found that when there's too much calcium channel activity in the prefrontal cortex, the neurons there don't fire as much, which makes it harder to think clearly. They published their findings in a scientific journal called JAMA Psychiatry on May 22.
"Trying to learn what causes these complex cognitive disorders is an enormous challenge, especially when they're attacking our most recently evolved brain circuits — you can't just mimic this in a dish," says Amy Arnsten, PhD, the study's senior author. "Studies like this are some of the rare bridges between the molecular biology and the symptoms we see in humans, allowing us to understand what these circuits need to function properly, as well as their vulnerabilities."
The researchers looked closely at a group of cells called layer III pyramidal cells, which are neurons in the prefrontal cortex that are very important for the brain's executive functions, like abstract thinking and working memory. These cells are more likely to shrink and die while their nearby neighbors usually stay healthy.
The team used different methods to study these neurons in humans and animals. They found that these neurons had a lot of calcium-related proteins, which means they need higher calcium levels to work properly.
The researchers then did more detailed studies, including in animal models. They discovered that the higher calcium levels in these pyramidal cells are necessary for higher thinking. "We found evidence that these neurons require higher calcium to maintain their firing over many seconds to represent information that isn't actually happening," says Arnsten. "That's the foundation of abstract thought."
When the team used a drug to mimic stress near the prefrontal neurons, they found that stress activated the calcium channels, which then opened nearby potassium channels and stopped the neurons from firing. "Ever have your mind go blank when you get bad news or have to do public speaking?" said Arnsten. "That's likely involving this mechanism."
These findings are important for understanding diseases like schizophrenia and Alzheimer's, which both involve problems with the prefrontal cortex. Previous research has shown that mutations in CACNA1C that increase calcium levels can raise the risk for schizophrenia. This study suggests that the extra calcium from these mutations can lead to the shrinking of neurons seen in the condition.
The team also found that the pyramidal cells contain a protein called calbindin, which helps keep calcium levels balanced. However, as we age or experience inflammation, this balance can be disrupted. In Alzheimer's disease, tau proteins can become tangled in the brain when calcium levels are too high. So, as the pyramidal cells in the prefrontal cortex get older and lose calbindin, they become more likely to develop Alzheimer's.
Arnsten hopes these discoveries will help scientists better understand and treat these conditions. "We've uncovered big clues about which brain cells are most vulnerable and which are resilient," she says. "If we can learn why certain cells are vulnerable, that also gives us clues about how to protect them."""